server:
  servlet:
    encoding:
      force: 'true'
      enabled: 'true'
      charset: UTF-8
    context-path: /toyboard
  port: '8080'
logging:
  level:
    org:
      springframework:
        web: DEBUG
redis:
  port: '6379'
  host: localhost

spring:
  datasource:
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    url: jdbc:mysql://localhost:3306/toyboard?serverTimezone=Asia/Seoul&useSSL=false
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    open-in-view: 'true'
    show_sql: 'true'
    properties:
      hibernate:
        format_sql: 'true'
  jackson:
    serialization:
      fail-on-empty-beans: 'false'
